// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin/cmd (interfaces: AutoCmd)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of AutoCmd interface
type MockAutoCmd struct {
	ctrl     *gomock.Controller
	recorder *_MockAutoCmdRecorder
}

// Recorder for MockAutoCmd (not exported)
type _MockAutoCmdRecorder struct {
	mock *MockAutoCmd
}

func NewMockAutoCmd(ctrl *gomock.Controller) *MockAutoCmd {
	mock := &MockAutoCmd{ctrl: ctrl}
	mock.recorder = &_MockAutoCmdRecorder{mock}
	return mock
}

func (_m *MockAutoCmd) EXPECT() *_MockAutoCmdRecorder {
	return _m.recorder
}

func (_m *MockAutoCmd) Run() error {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoCmdRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}
