// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin/cmd (interfaces: AutoTrustCmd)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of AutoTrustCmd interface
type MockAutoTrustCmd struct {
	ctrl     *gomock.Controller
	recorder *_MockAutoTrustCmdRecorder
}

// Recorder for MockAutoTrustCmd (not exported)
type _MockAutoTrustCmdRecorder struct {
	mock *MockAutoTrustCmd
}

func NewMockAutoTrustCmd(ctrl *gomock.Controller) *MockAutoTrustCmd {
	mock := &MockAutoTrustCmd{ctrl: ctrl}
	mock.recorder = &_MockAutoTrustCmdRecorder{mock}
	return mock
}

func (_m *MockAutoTrustCmd) EXPECT() *_MockAutoTrustCmdRecorder {
	return _m.recorder
}

func (_m *MockAutoTrustCmd) Run() error {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoTrustCmdRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}
