// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin/cmd (interfaces: CertStore)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of CertStore interface
type MockCertStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCertStoreRecorder
}

// Recorder for MockCertStore (not exported)
type _MockCertStoreRecorder struct {
	mock *MockCertStore
}

func NewMockCertStore(ctrl *gomock.Controller) *MockCertStore {
	mock := &MockCertStore{ctrl: ctrl}
	mock.recorder = &_MockCertStoreRecorder{mock}
	return mock
}

func (_m *MockCertStore) EXPECT() *_MockCertStoreRecorder {
	return _m.recorder
}

func (_m *MockCertStore) Unstore() error {
	ret := _m.ctrl.Call(_m, "Unstore")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCertStoreRecorder) Unstore() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unstore")
}
