// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin/cmd (interfaces: Cmd)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Cmd interface
type MockCmd struct {
	ctrl     *gomock.Controller
	recorder *_MockCmdRecorder
}

// Recorder for MockCmd (not exported)
type _MockCmdRecorder struct {
	mock *MockCmd
}

func NewMockCmd(ctrl *gomock.Controller) *MockCmd {
	mock := &MockCmd{ctrl: ctrl}
	mock.recorder = &_MockCmdRecorder{mock}
	return mock
}

func (_m *MockCmd) EXPECT() *_MockCmdRecorder {
	return _m.recorder
}

func (_m *MockCmd) Parse(_param0 []string) error {
	ret := _m.ctrl.Call(_m, "Parse", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCmdRecorder) Parse(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Parse", arg0)
}

func (_m *MockCmd) Run() error {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCmdRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}
