// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin/cmd (interfaces: DownloaderFactory)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	downloader "github.com/pivotal-cf/pcfdev-cli/downloader"
)

// Mock of DownloaderFactory interface
type MockDownloaderFactory struct {
	ctrl     *gomock.Controller
	recorder *_MockDownloaderFactoryRecorder
}

// Recorder for MockDownloaderFactory (not exported)
type _MockDownloaderFactoryRecorder struct {
	mock *MockDownloaderFactory
}

func NewMockDownloaderFactory(ctrl *gomock.Controller) *MockDownloaderFactory {
	mock := &MockDownloaderFactory{ctrl: ctrl}
	mock.recorder = &_MockDownloaderFactoryRecorder{mock}
	return mock
}

func (_m *MockDownloaderFactory) EXPECT() *_MockDownloaderFactoryRecorder {
	return _m.recorder
}

func (_m *MockDownloaderFactory) Create() (downloader.Downloader, error) {
	ret := _m.ctrl.Call(_m, "Create")
	ret0, _ := ret[0].(downloader.Downloader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDownloaderFactoryRecorder) Create() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create")
}
