// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin/cmd (interfaces: VBoxDriver)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	vbox "github.com/pivotal-cf/pcfdev-cli/vbox"
)

// Mock of VBoxDriver interface
type MockVBoxDriver struct {
	ctrl     *gomock.Controller
	recorder *_MockVBoxDriverRecorder
}

// Recorder for MockVBoxDriver (not exported)
type _MockVBoxDriverRecorder struct {
	mock *MockVBoxDriver
}

func NewMockVBoxDriver(ctrl *gomock.Controller) *MockVBoxDriver {
	mock := &MockVBoxDriver{ctrl: ctrl}
	mock.recorder = &_MockVBoxDriverRecorder{mock}
	return mock
}

func (_m *MockVBoxDriver) EXPECT() *_MockVBoxDriverRecorder {
	return _m.recorder
}

func (_m *MockVBoxDriver) Version() (*vbox.VBoxDriverVersion, error) {
	ret := _m.ctrl.Call(_m, "Version")
	ret0, _ := ret[0].(*vbox.VBoxDriverVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVBoxDriverRecorder) Version() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Version")
}
