// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/downloader (interfaces: Token)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Token interface
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *_MockTokenRecorder
}

// Recorder for MockToken (not exported)
type _MockTokenRecorder struct {
	mock *MockToken
}

func NewMockToken(ctrl *gomock.Controller) *MockToken {
	mock := &MockToken{ctrl: ctrl}
	mock.recorder = &_MockTokenRecorder{mock}
	return mock
}

func (_m *MockToken) EXPECT() *_MockTokenRecorder {
	return _m.recorder
}

func (_m *MockToken) Save() error {
	ret := _m.ctrl.Call(_m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockTokenRecorder) Save() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save")
}
