// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/ui (interfaces: TextScroller)

package mocks

import (
	termui "github.com/gizak/termui"
	gomock "github.com/golang/mock/gomock"
)

// Mock of TextScroller interface
type MockTextScroller struct {
	ctrl     *gomock.Controller
	recorder *_MockTextScrollerRecorder
}

// Recorder for MockTextScroller (not exported)
type _MockTextScrollerRecorder struct {
	mock *MockTextScroller
}

func NewMockTextScroller(ctrl *gomock.Controller) *MockTextScroller {
	mock := &MockTextScroller{ctrl: ctrl}
	mock.recorder = &_MockTextScrollerRecorder{mock}
	return mock
}

func (_m *MockTextScroller) EXPECT() *_MockTextScrollerRecorder {
	return _m.recorder
}

func (_m *MockTextScroller) Buffer() termui.Buffer {
	ret := _m.ctrl.Call(_m, "Buffer")
	ret0, _ := ret[0].(termui.Buffer)
	return ret0
}

func (_mr *_MockTextScrollerRecorder) Buffer() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Buffer")
}

func (_m *MockTextScroller) End() {
	_m.ctrl.Call(_m, "End")
}

func (_mr *_MockTextScrollerRecorder) End() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "End")
}

func (_m *MockTextScroller) Home() {
	_m.ctrl.Call(_m, "Home")
}

func (_mr *_MockTextScrollerRecorder) Home() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Home")
}

func (_m *MockTextScroller) PageDown() {
	_m.ctrl.Call(_m, "PageDown")
}

func (_mr *_MockTextScrollerRecorder) PageDown() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PageDown")
}

func (_m *MockTextScroller) PageUp() {
	_m.ctrl.Call(_m, "PageUp")
}

func (_mr *_MockTextScrollerRecorder) PageUp() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PageUp")
}

func (_m *MockTextScroller) Resize(_param0 int, _param1 int) {
	_m.ctrl.Call(_m, "Resize", _param0, _param1)
}

func (_mr *_MockTextScrollerRecorder) Resize(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Resize", arg0, arg1)
}

func (_m *MockTextScroller) ScrollDown() {
	_m.ctrl.Call(_m, "ScrollDown")
}

func (_mr *_MockTextScrollerRecorder) ScrollDown() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ScrollDown")
}

func (_m *MockTextScroller) ScrollUp() {
	_m.ctrl.Call(_m, "ScrollUp")
}

func (_mr *_MockTextScrollerRecorder) ScrollUp() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ScrollUp")
}

func (_m *MockTextScroller) SetText(_param0 string) {
	_m.ctrl.Call(_m, "SetText", _param0)
}

func (_mr *_MockTextScrollerRecorder) SetText(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetText", arg0)
}
