// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/requirements (interfaces: MemoryChecker)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of MemoryChecker interface
type MockMemoryChecker struct {
	ctrl     *gomock.Controller
	recorder *_MockMemoryCheckerRecorder
}

// Recorder for MockMemoryChecker (not exported)
type _MockMemoryCheckerRecorder struct {
	mock *MockMemoryChecker
}

func NewMockMemoryChecker(ctrl *gomock.Controller) *MockMemoryChecker {
	mock := &MockMemoryChecker{ctrl: ctrl}
	mock.recorder = &_MockMemoryCheckerRecorder{mock}
	return mock
}

func (_m *MockMemoryChecker) EXPECT() *_MockMemoryCheckerRecorder {
	return _m.recorder
}

func (_m *MockMemoryChecker) Check() error {
	ret := _m.ctrl.Call(_m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockMemoryCheckerRecorder) Check() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Check")
}
