// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/requirements (interfaces: System)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of System interface
type MockSystem struct {
	ctrl     *gomock.Controller
	recorder *_MockSystemRecorder
}

// Recorder for MockSystem (not exported)
type _MockSystemRecorder struct {
	mock *MockSystem
}

func NewMockSystem(ctrl *gomock.Controller) *MockSystem {
	mock := &MockSystem{ctrl: ctrl}
	mock.recorder = &_MockSystemRecorder{mock}
	return mock
}

func (_m *MockSystem) EXPECT() *_MockSystemRecorder {
	return _m.recorder
}

func (_m *MockSystem) FreeMemory() (uint64, error) {
	ret := _m.ctrl.Call(_m, "FreeMemory")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSystemRecorder) FreeMemory() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FreeMemory")
}
