// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/network (interfaces: NetConfig)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	net "net"
)

// Mock of NetConfig interface
type MockNetConfig struct {
	ctrl     *gomock.Controller
	recorder *_MockNetConfigRecorder
}

// Recorder for MockNetConfig (not exported)
type _MockNetConfigRecorder struct {
	mock *MockNetConfig
}

func NewMockNetConfig(ctrl *gomock.Controller) *MockNetConfig {
	mock := &MockNetConfig{ctrl: ctrl}
	mock.recorder = &_MockNetConfigRecorder{mock}
	return mock
}

func (_m *MockNetConfig) EXPECT() *_MockNetConfigRecorder {
	return _m.recorder
}

func (_m *MockNetConfig) InterfaceAddrs() ([]net.Addr, error) {
	ret := _m.ctrl.Call(_m, "InterfaceAddrs")
	ret0, _ := ret[0].([]net.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNetConfigRecorder) InterfaceAddrs() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "InterfaceAddrs")
}
