// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/address (interfaces: Driver)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Driver interface
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *_MockDriverRecorder
}

// Recorder for MockDriver (not exported)
type _MockDriverRecorder struct {
	mock *MockDriver
}

func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &_MockDriverRecorder{mock}
	return mock
}

func (_m *MockDriver) EXPECT() *_MockDriverRecorder {
	return _m.recorder
}

func (_m *MockDriver) IsInterfaceInUse(_param0 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "IsInterfaceInUse", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDriverRecorder) IsInterfaceInUse(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsInterfaceInUse", arg0)
}
