// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/address (interfaces: Network)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	network "github.com/pivotal-cf/pcfdev-cli/network"
)

// Mock of Network interface
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *_MockNetworkRecorder
}

// Recorder for MockNetwork (not exported)
type _MockNetworkRecorder struct {
	mock *MockNetwork
}

func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &_MockNetworkRecorder{mock}
	return mock
}

func (_m *MockNetwork) EXPECT() *_MockNetworkRecorder {
	return _m.recorder
}

func (_m *MockNetwork) Interfaces() ([]*network.Interface, error) {
	ret := _m.ctrl.Call(_m, "Interfaces")
	ret0, _ := ret[0].([]*network.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNetworkRecorder) Interfaces() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Interfaces")
}
