// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/pivnet (interfaces: PivnetClient)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of PivnetClient interface
type MockPivnetClient struct {
	ctrl     *gomock.Controller
	recorder *_MockPivnetClientRecorder
}

// Recorder for MockPivnetClient (not exported)
type _MockPivnetClientRecorder struct {
	mock *MockPivnetClient
}

func NewMockPivnetClient(ctrl *gomock.Controller) *MockPivnetClient {
	mock := &MockPivnetClient{ctrl: ctrl}
	mock.recorder = &_MockPivnetClientRecorder{mock}
	return mock
}

func (_m *MockPivnetClient) EXPECT() *_MockPivnetClientRecorder {
	return _m.recorder
}

func (_m *MockPivnetClient) GetToken(_param0 string, _param1 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetToken", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPivnetClientRecorder) GetToken(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetToken", arg0, arg1)
}
