// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/pivnet (interfaces: UI)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of UI interface
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *_MockUIRecorder
}

// Recorder for MockUI (not exported)
type _MockUIRecorder struct {
	mock *MockUI
}

func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &_MockUIRecorder{mock}
	return mock
}

func (_m *MockUI) EXPECT() *_MockUIRecorder {
	return _m.recorder
}

func (_m *MockUI) AskForPassword(_param0 string, _param1 ...interface{}) string {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "AskForPassword", _s...)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockUIRecorder) AskForPassword(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AskForPassword", _s...)
}
