// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vm (interfaces: CertStore)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of CertStore interface
type MockCertStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCertStoreRecorder
}

// Recorder for MockCertStore (not exported)
type _MockCertStoreRecorder struct {
	mock *MockCertStore
}

func NewMockCertStore(ctrl *gomock.Controller) *MockCertStore {
	mock := &MockCertStore{ctrl: ctrl}
	mock.recorder = &_MockCertStoreRecorder{mock}
	return mock
}

func (_m *MockCertStore) EXPECT() *_MockCertStoreRecorder {
	return _m.recorder
}

func (_m *MockCertStore) Store(_param0 string) error {
	ret := _m.ctrl.Call(_m, "Store", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCertStoreRecorder) Store(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Store", arg0)
}
