// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vm (interfaces: HelpText)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of HelpText interface
type MockHelpText struct {
	ctrl     *gomock.Controller
	recorder *_MockHelpTextRecorder
}

// Recorder for MockHelpText (not exported)
type _MockHelpTextRecorder struct {
	mock *MockHelpText
}

func NewMockHelpText(ctrl *gomock.Controller) *MockHelpText {
	mock := &MockHelpText{ctrl: ctrl}
	mock.recorder = &_MockHelpTextRecorder{mock}
	return mock
}

func (_m *MockHelpText) EXPECT() *_MockHelpTextRecorder {
	return _m.recorder
}

func (_m *MockHelpText) Print(_param0 string, _param1 bool) {
	_m.ctrl.Call(_m, "Print", _param0, _param1)
}

func (_mr *_MockHelpTextRecorder) Print(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Print", arg0, arg1)
}
