// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vm (interfaces: LogFetcher)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of LogFetcher interface
type MockLogFetcher struct {
	ctrl     *gomock.Controller
	recorder *_MockLogFetcherRecorder
}

// Recorder for MockLogFetcher (not exported)
type _MockLogFetcherRecorder struct {
	mock *MockLogFetcher
}

func NewMockLogFetcher(ctrl *gomock.Controller) *MockLogFetcher {
	mock := &MockLogFetcher{ctrl: ctrl}
	mock.recorder = &_MockLogFetcherRecorder{mock}
	return mock
}

func (_m *MockLogFetcher) EXPECT() *_MockLogFetcherRecorder {
	return _m.recorder
}

func (_m *MockLogFetcher) FetchLogs() error {
	ret := _m.ctrl.Call(_m, "FetchLogs")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockLogFetcherRecorder) FetchLogs() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchLogs")
}
