// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vbox (interfaces: Config)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Config interface
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *_MockConfigRecorder
}

// Recorder for MockConfig (not exported)
type _MockConfigRecorder struct {
	mock *MockConfig
}

func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &_MockConfigRecorder{mock}
	return mock
}

func (_m *MockConfig) EXPECT() *_MockConfigRecorder {
	return _m.recorder
}

func (_m *MockConfig) GetDesiredMemory() (uint64, error) {
	ret := _m.ctrl.Call(_m, "GetDesiredMemory")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConfigRecorder) GetDesiredMemory() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetDesiredMemory")
}

func (_m *MockConfig) GetMaxMemory() uint64 {
	ret := _m.ctrl.Call(_m, "GetMaxMemory")
	ret0, _ := ret[0].(uint64)
	return ret0
}

func (_mr *_MockConfigRecorder) GetMaxMemory() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetMaxMemory")
}

func (_m *MockConfig) GetMinMemory() uint64 {
	ret := _m.ctrl.Call(_m, "GetMinMemory")
	ret0, _ := ret[0].(uint64)
	return ret0
}

func (_mr *_MockConfigRecorder) GetMinMemory() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetMinMemory")
}
