// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vbox (interfaces: Driver)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Driver interface
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *_MockDriverRecorder
}

// Recorder for MockDriver (not exported)
type _MockDriverRecorder struct {
	mock *MockDriver
}

func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &_MockDriverRecorder{mock}
	return mock
}

func (_m *MockDriver) EXPECT() *_MockDriverRecorder {
	return _m.recorder
}

func (_m *MockDriver) AttachNetworkInterface(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "AttachNetworkInterface", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDriverRecorder) AttachNetworkInterface(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachNetworkInterface", arg0, arg1)
}

func (_m *MockDriver) CreateHostOnlyInterface(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "CreateHostOnlyInterface", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDriverRecorder) CreateHostOnlyInterface(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateHostOnlyInterface", arg0)
}

func (_m *MockDriver) DestroyVM(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DestroyVM", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDriverRecorder) DestroyVM(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DestroyVM", arg0)
}

func (_m *MockDriver) ForwardPort(_param0 string, _param1 string, _param2 string, _param3 string) error {
	ret := _m.ctrl.Call(_m, "ForwardPort", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDriverRecorder) ForwardPort(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ForwardPort", arg0, arg1, arg2, arg3)
}

func (_m *MockDriver) GetHostForwardPort(_param0 string, _param1 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetHostForwardPort", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDriverRecorder) GetHostForwardPort(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetHostForwardPort", arg0, arg1)
}

func (_m *MockDriver) IsVMRunning(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "IsVMRunning", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockDriverRecorder) IsVMRunning(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsVMRunning", arg0)
}

func (_m *MockDriver) StartVM(_param0 string) error {
	ret := _m.ctrl.Call(_m, "StartVM", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDriverRecorder) StartVM(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StartVM", arg0)
}

func (_m *MockDriver) StopVM(_param0 string) error {
	ret := _m.ctrl.Call(_m, "StopVM", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDriverRecorder) StopVM(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StopVM", arg0)
}

func (_m *MockDriver) VBoxManage(_param0 ...string) ([]byte, error) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "VBoxManage", _s...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDriverRecorder) VBoxManage(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "VBoxManage", arg0...)
}

func (_m *MockDriver) VMExists(_param0 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "VMExists", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDriverRecorder) VMExists(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "VMExists", arg0)
}
