// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vbox (interfaces: NetworkPicker)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	network "github.com/pivotal-cf/pcfdev-cli/network"
)

// Mock of NetworkPicker interface
type MockNetworkPicker struct {
	ctrl     *gomock.Controller
	recorder *_MockNetworkPickerRecorder
}

// Recorder for MockNetworkPicker (not exported)
type _MockNetworkPickerRecorder struct {
	mock *MockNetworkPicker
}

func NewMockNetworkPicker(ctrl *gomock.Controller) *MockNetworkPicker {
	mock := &MockNetworkPicker{ctrl: ctrl}
	mock.recorder = &_MockNetworkPickerRecorder{mock}
	return mock
}

func (_m *MockNetworkPicker) EXPECT() *_MockNetworkPickerRecorder {
	return _m.recorder
}

func (_m *MockNetworkPicker) SelectAvailableNetworkInterface(_param0 []*network.Interface) (*network.Interface, bool, error) {
	ret := _m.ctrl.Call(_m, "SelectAvailableNetworkInterface", _param0)
	ret0, _ := ret[0].(*network.Interface)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockNetworkPickerRecorder) SelectAvailableNetworkInterface(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SelectAvailableNetworkInterface", arg0)
}
