// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vbox (interfaces: Pinger)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Pinger interface
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *_MockPingerRecorder
}

// Recorder for MockPinger (not exported)
type _MockPingerRecorder struct {
	mock *MockPinger
}

func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &_MockPingerRecorder{mock}
	return mock
}

func (_m *MockPinger) EXPECT() *_MockPingerRecorder {
	return _m.recorder
}

func (_m *MockPinger) TryIP(_param0 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "TryIP", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPingerRecorder) TryIP(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TryIP", arg0)
}
