// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vbox (interfaces: VBoxSystemConfiguration)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of VBoxSystemConfiguration interface
type MockVBoxSystemConfiguration struct {
	ctrl     *gomock.Controller
	recorder *_MockVBoxSystemConfigurationRecorder
}

// Recorder for MockVBoxSystemConfiguration (not exported)
type _MockVBoxSystemConfigurationRecorder struct {
	mock *MockVBoxSystemConfiguration
}

func NewMockVBoxSystemConfiguration(ctrl *gomock.Controller) *MockVBoxSystemConfiguration {
	mock := &MockVBoxSystemConfiguration{ctrl: ctrl}
	mock.recorder = &_MockVBoxSystemConfigurationRecorder{mock}
	return mock
}

func (_m *MockVBoxSystemConfiguration) EXPECT() *_MockVBoxSystemConfigurationRecorder {
	return _m.recorder
}

func (_m *MockVBoxSystemConfiguration) EnvironmentConfiguration(_param0 string, _param1 string, _param2 string, _param3 string, _param4 string) (string, error) {
	ret := _m.ctrl.Call(_m, "EnvironmentConfiguration", _param0, _param1, _param2, _param3, _param4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVBoxSystemConfigurationRecorder) EnvironmentConfiguration(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EnvironmentConfiguration", arg0, arg1, arg2, arg3, arg4)
}

func (_m *MockVBoxSystemConfiguration) NetworkConfiguration(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "NetworkConfiguration", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVBoxSystemConfigurationRecorder) NetworkConfiguration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NetworkConfiguration", arg0)
}
