// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/ping (interfaces: User)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of User interface
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *_MockUserRecorder
}

// Recorder for MockUser (not exported)
type _MockUserRecorder struct {
	mock *MockUser
}

func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &_MockUserRecorder{mock}
	return mock
}

func (_m *MockUser) EXPECT() *_MockUserRecorder {
	return _m.recorder
}

func (_m *MockUser) IsPrivileged() (bool, error) {
	ret := _m.ctrl.Call(_m, "IsPrivileged")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockUserRecorder) IsPrivileged() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsPrivileged")
}
