// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin (interfaces: Builder)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	vm "github.com/pivotal-cf/pcfdev-cli/vm"
)

// Mock of Builder interface
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *_MockBuilderRecorder
}

// Recorder for MockBuilder (not exported)
type _MockBuilderRecorder struct {
	mock *MockBuilder
}

func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &_MockBuilderRecorder{mock}
	return mock
}

func (_m *MockBuilder) EXPECT() *_MockBuilderRecorder {
	return _m.recorder
}

func (_m *MockBuilder) VM(_param0 string) (vm.VM, error) {
	ret := _m.ctrl.Call(_m, "VM", _param0)
	ret0, _ := ret[0].(vm.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockBuilderRecorder) VM(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "VM", arg0)
}
