// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin (interfaces: CmdBuilder)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	cmd "github.com/pivotal-cf/pcfdev-cli/plugin/cmd"
)

// Mock of CmdBuilder interface
type MockCmdBuilder struct {
	ctrl     *gomock.Controller
	recorder *_MockCmdBuilderRecorder
}

// Recorder for MockCmdBuilder (not exported)
type _MockCmdBuilderRecorder struct {
	mock *MockCmdBuilder
}

func NewMockCmdBuilder(ctrl *gomock.Controller) *MockCmdBuilder {
	mock := &MockCmdBuilder{ctrl: ctrl}
	mock.recorder = &_MockCmdBuilderRecorder{mock}
	return mock
}

func (_m *MockCmdBuilder) EXPECT() *_MockCmdBuilderRecorder {
	return _m.recorder
}

func (_m *MockCmdBuilder) Cmd(_param0 string) (cmd.Cmd, error) {
	ret := _m.ctrl.Call(_m, "Cmd", _param0)
	ret0, _ := ret[0].(cmd.Cmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCmdBuilderRecorder) Cmd(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Cmd", arg0)
}
