// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin (interfaces: Exit)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Exit interface
type MockExit struct {
	ctrl     *gomock.Controller
	recorder *_MockExitRecorder
}

// Recorder for MockExit (not exported)
type _MockExitRecorder struct {
	mock *MockExit
}

func NewMockExit(ctrl *gomock.Controller) *MockExit {
	mock := &MockExit{ctrl: ctrl}
	mock.recorder = &_MockExitRecorder{mock}
	return mock
}

func (_m *MockExit) EXPECT() *_MockExitRecorder {
	return _m.recorder
}

func (_m *MockExit) Exit(_param0 int) {
	_m.ctrl.Call(_m, "Exit", _param0)
}

func (_mr *_MockExitRecorder) Exit(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Exit", arg0)
}
