// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin (interfaces: Requirements)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Requirements interface
type MockRequirements struct {
	ctrl     *gomock.Controller
	recorder *_MockRequirementsRecorder
}

// Recorder for MockRequirements (not exported)
type _MockRequirementsRecorder struct {
	mock *MockRequirements
}

func NewMockRequirements(ctrl *gomock.Controller) *MockRequirements {
	mock := &MockRequirements{ctrl: ctrl}
	mock.recorder = &_MockRequirementsRecorder{mock}
	return mock
}

func (_m *MockRequirements) EXPECT() *_MockRequirementsRecorder {
	return _m.recorder
}

func (_m *MockRequirements) CheckRequirements() bool {
	ret := _m.ctrl.Call(_m, "CheckRequirements")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockRequirementsRecorder) CheckRequirements() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CheckRequirements")
}
