// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin (interfaces: VBox)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	vbox "github.com/pivotal-cf/pcfdev-cli/vbox"
)

// Mock of VBox interface
type MockVBox struct {
	ctrl     *gomock.Controller
	recorder *_MockVBoxRecorder
}

// Recorder for MockVBox (not exported)
type _MockVBoxRecorder struct {
	mock *MockVBox
}

func NewMockVBox(ctrl *gomock.Controller) *MockVBox {
	mock := &MockVBox{ctrl: ctrl}
	mock.recorder = &_MockVBoxRecorder{mock}
	return mock
}

func (_m *MockVBox) EXPECT() *_MockVBoxRecorder {
	return _m.recorder
}

func (_m *MockVBox) IsVMRunning(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "IsVMRunning", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockVBoxRecorder) IsVMRunning(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsVMRunning", arg0)
}

func (_m *MockVBox) StartVM(_param0 string, _param1 string) (*vbox.VM, error) {
	ret := _m.ctrl.Call(_m, "StartVM", _param0, _param1)
	ret0, _ := ret[0].(*vbox.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVBoxRecorder) StartVM(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StartVM", arg0, arg1)
}

func (_m *MockVBox) StopVM(_param0 string) error {
	ret := _m.ctrl.Call(_m, "StopVM", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVBoxRecorder) StopVM(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StopVM", arg0)
}
