// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/plugin (interfaces: VBox)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of VBox interface
type MockVBox struct {
	ctrl     *gomock.Controller
	recorder *_MockVBoxRecorder
}

// Recorder for MockVBox (not exported)
type _MockVBoxRecorder struct {
	mock *MockVBox
}

func NewMockVBox(ctrl *gomock.Controller) *MockVBox {
	mock := &MockVBox{ctrl: ctrl}
	mock.recorder = &_MockVBoxRecorder{mock}
	return mock
}

func (_m *MockVBox) EXPECT() *_MockVBoxRecorder {
	return _m.recorder
}

func (_m *MockVBox) DestroyVMs(_param0 []string) error {
	ret := _m.ctrl.Call(_m, "DestroyVMs", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVBoxRecorder) DestroyVMs(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DestroyVMs", arg0)
}

func (_m *MockVBox) GetPCFDevVMs() ([]string, error) {
	ret := _m.ctrl.Call(_m, "GetPCFDevVMs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVBoxRecorder) GetPCFDevVMs() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPCFDevVMs")
}
