// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/pcfdev-cli/vm (interfaces: VM)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of VM interface
type MockVM struct {
	ctrl     *gomock.Controller
	recorder *_MockVMRecorder
}

// Recorder for MockVM (not exported)
type _MockVMRecorder struct {
	mock *MockVM
}

func NewMockVM(ctrl *gomock.Controller) *MockVM {
	mock := &MockVM{ctrl: ctrl}
	mock.recorder = &_MockVMRecorder{mock}
	return mock
}

func (_m *MockVM) EXPECT() *_MockVMRecorder {
	return _m.recorder
}

func (_m *MockVM) Start() error {
	ret := _m.ctrl.Call(_m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVMRecorder) Start() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Start")
}

func (_m *MockVM) Status() {
	_m.ctrl.Call(_m, "Status")
}

func (_mr *_MockVMRecorder) Status() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Status")
}

func (_m *MockVM) Stop() error {
	ret := _m.ctrl.Call(_m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVMRecorder) Stop() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Stop")
}
